# Generated by Django 3.2.7 on 2021-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_category_cat_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
