# Generated by Django 3.2.7 on 2021-12-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.blog')),
            ],
        ),
    ]
